services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  test:
    build: .
    command: ["python", "-m", "pytest", "tests/unit/", "-v", "-o", "log_cli_level=DEBUG"]
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=testing

  validation:
    build: .
    command: ["python", "validation/run_validation.py"]
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=validation