services:
  web:
    container_name: ocel-web
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  # test:
  #   container_name: ocel-test
  #   build: .
  #   command:
  #     [
  #       "python",
  #       "-m",
  #       "pytest",
  #       "tests/unit/",
  #       "-v",
  #       "-o",
  #       "log_cli_level=DEBUG",
  #     ]
  #   volumes:
  #     - .:/app
  #   environment:
  #     - FLASK_ENV=testing

  validation:
    container_name: ocel-validation
    build: .
    command:
      [
        "python",
        "validation/run_validation.py",
        "--event_attr_pct",
        "30",
        "--object_pct",
        "20",
        "--object_attr_pct",
        "40",
      ]
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=validation
      - PYTHONPATH=/app 