# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("1440x1024")
window.configure(bg="#ffffff")
window.title("Log")

canvas = tk.Canvas(
    window,
    bg = "#ffffff",
    width = 1440,
    height = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

image_13 = tk.PhotoImage(file=load_asset("frame_2/1.png"))

canvas.create_image(721, 78, image=image_13)

image_14 = tk.PhotoImage(file=load_asset("frame_2/2.png"))

canvas.create_image(158, 73, image=image_14)

image_15 = tk.PhotoImage(file=load_asset("frame_2/3.png"))

canvas.create_image(720, 154, image=image_15)

image_16 = tk.PhotoImage(file=load_asset("frame_2/4.png"))

canvas.create_image(719, 341, image=image_16)

image_17 = tk.PhotoImage(file=load_asset("frame_2/5.png"))

canvas.create_image(713, 375, image=image_17)

canvas.create_text(
    111,
    257,
    anchor="nw",
    text="Detected keys in supported file formats",
    fill="#1e1e1e",
    font=("Inter", 24 * -1)
)

image_18 = tk.PhotoImage(file=load_asset("frame_2/6.png"))

canvas.create_image(719, 612, image=image_18)

image_19 = tk.PhotoImage(file=load_asset("frame_2/7.png"))

canvas.create_image(713, 646, image=image_19)

canvas.create_text(
    111,
    526,
    anchor="nw",
    text="Detected sub-keys in supported file formats",
    fill="#1e1e1e",
    font=("Inter", 24 * -1)
)

image_20 = tk.PhotoImage(file=load_asset("frame_2/8.png"))

canvas.create_image(411, 857, image=image_20)

image_21 = tk.PhotoImage(file=load_asset("frame_2/9.png"))

canvas.create_image(410, 891, image=image_21)

canvas.create_text(
    111,
    771,
    anchor="nw",
    text="Statistics of selected file",
    fill="#1e1e1e",
    font=("Inter", 24 * -1)
)

button_5_image = tk.PhotoImage(file=load_asset("frame_2/10.png"))

button_5 = tk.Button(
    image=button_5_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 has been pressed!")
)

button_5.place(x=1129, y=858, width=267, height=76)

button_6_image = tk.PhotoImage(file=load_asset("frame_2/11.png"))

button_6 = tk.Button(
    image=button_6_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 has been pressed!")
)

button_6.place(x=854, y=858, width=242, height=76)

image_22 = tk.PhotoImage(file=load_asset("frame_2/12.png"))

canvas.create_image(891, 895, image=image_22)

image_23 = tk.PhotoImage(file=load_asset("frame_2/13.png"))

canvas.create_image(78, 784, image=image_23)

image_24 = tk.PhotoImage(file=load_asset("frame_2/14.png"))

canvas.create_image(78, 537, image=image_24)

window.resizable(False, False)
window.mainloop()
